[package]
name = "rogue_mogle"
version = "0.1.0"
authors = ["Arne Bargholz <bargholz@theochem.uni-stuttgart.de>"]

[dependencies]

vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"

winit = "0.18"
