[package]
name = "rogue_mogle"
version = "0.1.0"
authors = ["Arne <arne.zxy333@gmail.com>"]
publish = false

include = ["src/**/*","src/resources/shader/*.glsl"]

[dependencies]


cgmath = "0.16.1"
vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"

winit = "0.18"
